# Generated by Django 3.2.6 on 2021-08-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappregis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
