# Generated by Django 3.2.6 on 2021-08-25 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappregis', '0002_auto_20210825_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 8, 25), max_length=8),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
    ]
