# Generated by Django 3.2.6 on 2021-08-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappregis', '0003_auto_20210825_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='lastname',
        ),
    ]
